# Generated by Django 4.2 on 2023-04-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavolTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texnologiya', models.CharField(max_length=30)),
                ('savol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.savol')),
            ],
        ),
    ]
