# Generated by Django 4.2 on 2023-04-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_alter_savol_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='savol',
            name='texnologiya',
            field=models.CharField(default='Python', max_length=30),
        ),
        migrations.DeleteModel(
            name='SavolTag',
        ),
    ]
